### ISSUE TITLE
"MimicMotionNode” Not Found. :/

### ISSUE THREAD

**Issue by leetraman822** [AIFSH/ComfyUI-MimicMotion#7]
Hi, I already installed requirements, but after importing the workflow, it told me that MimicMotionNode and PreVideo were missing. I installed ComfyUI-IP_LAP and ComfyUI-3d-photo-inpainting using the feature to install missing nodes. I don't know what these nodes are for, but after restarting ComfyUI, PreVideo no longer showed an error, but MimicMotionNode still missing.
I tried reinstalling and updating this node, but it still shows this error, and the terminal keeps showing IMPORT FAILED.

   0.1 seconds (IMPORT FAILED): E:\StableDiffusion\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-I2V-Adapter
   1.2 seconds (IMPORT FAILED): E:\StableDiffusion\ComfyUI_windows\ComfyUI\custom_nodes\ComfyUI-IP_LAP

**Comment by Hikska** [comment]
same here, it installed so many new nodes it flooded me with errors, i dont know what to look, i restarted multiple time, it feel like its missing many modules, or it works only on linux ?

`
D:\AI\ComfyUI_windows_portable>.\python_embeded\python.exe -s ComfyUI\main.py --windows-standalone-build
[START] Security scan
[DONE] Security scan
## ComfyUI-Manager: installing dependencies done.
** ComfyUI startup time: 2024-07-03 15:56:04.226760
** Platform: Windows
** Python version: 3.11.8 (tags/v3.11.8:db85d51, Feb  6 2024, 22:03:32) [MSC v.1937 64 bit (AMD64)]
** Python executable: D:\AI\ComfyUI_windows_portable\python_embeded\python.exe
** ComfyUI Path: D:\AI\ComfyUI_windows_portable\ComfyUI\main.py
** Log path: D:\AI\ComfyUI_windows_portable\comfyui.log

Prestartup times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.7 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager

Total VRAM 24564 MB, total RAM 65394 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
Using xformers cross attention
!!!3dphoto path was added to D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages/3dphoto.pth
 if meet No module named 'MiDas' error,please restart comfyui
3d-photo-inpainting use cache models,make sure your 'checkpoints' complete
[AnimateDiff] - WARNING - xformers is enabled but it has a bug that can cause issue while using with AnimateDiff.
Adding D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes to sys.path
Efficiency Nodes: Attempting to add Control Net options to the 'HiRes-Fix Script' Node (comfyui_controlnet_aux add-on)...Success!
Loaded Efficiency nodes from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
Loaded ControlNetPreprocessors nodes from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
Loaded AdvancedControlNet nodes from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
Loaded AnimateDiff from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff\animatediff/sliding_schedule.py
Could not find IPAdapter nodes
Loaded VideoHelperSuite from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
### Loading: ComfyUI-Impact-Pack (V5.18.4)
### Loading: ComfyUI-Impact-Pack (Subpack: V0.6)
### Loading: ComfyUI-Impact-Pack (V5.18.4)
Loaded ImpactPack nodes from D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
[Impact Pack] Wildcards loading done.
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\__init__.py", line 2, in <module>
    from .studio_nodes import DiffTextNode,DiffutoonNode,SDPathLoader,ControlNetPathLoader,ExVideoNode
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\studio_nodes.py", line 11, in <module>
    from diffsynth.data.video import crop_and_resize
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\__init__.py", line 5, in <module>
    from .pipelines import *
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\pipelines\__init__.py", line 1, in <module>
    from .stable_diffusion import SDImagePipeline
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\pipelines\stable_diffusion.py", line 2, in <module>
    from ..controlnets import MultiControlNetManager, ControlNetUnit, ControlNetConfigUnit, Annotator
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\__init__.py", line 1, in <module>
    from .controlnet_unit import ControlNetConfigUnit, ControlNetUnit, MultiControlNetManager
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\controlnet_unit.py", line 3, in <module>
    from .processors import Processor_id
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio\diffsynth\controlnets\processors.py", line 7, in <module>
    from controlnet_aux.processor import (
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\processor.py", line 10, in <module>
    from controlnet_aux import (CannyDetector, ContentShuffleDetector, HEDdetector,
ImportError: cannot import name 'CannyDetector' from 'controlnet_aux' (D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio module for custom nodes: cannot import name 'CannyDetector' from 'controlnet_aux' (D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux\src\controlnet_aux\__init__.py)
!!!Hallo path was added to D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages/Hallo.pth
 if meet No module named 'hallo' error,please restart comfyui
Hallo use cache models,make sure your 'pretrained_models' complete
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\__init__.py", line 33, in <module>
    from .nodes import PreViewVideo,HalloNode,LoadImagePath, LoadAudioPath
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\nodes.py", line 6, in <module>
    from Hallo.scripts.inference import inference_process
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo\Hallo\scripts\inference.py", line 35, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 4, in <module>
    from .onnx_utils import OnnxRuntimeModel
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\onnx_utils.py", line 31, in <module>
    import onnxruntime as ort
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo module for custom nodes: DLL load failed while importing onnxruntime_pybind11_state: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2V-Adapter\__init__.py", line 4, in <module>
    from .nodes import *
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2V-Adapter\nodes.py", line 15, in <module>
    from diffusers import AutoencoderKL, DDIMScheduler
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 4, in <module>
    from .onnx_utils import OnnxRuntimeModel
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\onnx_utils.py", line 31, in <module>
    import onnxruntime as ort
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2V-Adapter module for custom nodes: DLL load failed while importing onnxruntime_pybind11_state: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.
### Loading: ComfyUI-Impact-Pack (V5.18.4)
### Loading: ComfyUI-Inspire-Pack (V0.80.4)
[Impact Pack] Wildcards loading done.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IP_LAP\__init__.py", line 1, in <module>
    from .nodes import IP_LAP,LoadVideo,PreViewVideo,CombineAudioVideo
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IP_LAP\nodes.py", line 10, in <module>
    from .ip_lap.inference import IP_LAP_infer
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IP_LAP\ip_lap\inference.py", line 7, in <module>
    from .face_mask import FaceMask
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IP_LAP\ip_lap\face_mask.py", line 5, in <module>
    from basicsr.utils.download_util import load_file_from_url
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "importlib\__init__.py", line 126, in import_module
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IP_LAP module for custom nodes: No module named 'torchvision.transforms.functional_tensor'
Total VRAM 24564 MB, total RAM 65394 MB
pytorch version: 2.3.0+cu121
xformers version: 0.0.26.post1
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
### Loading: ComfyUI-Manager (V2.43)
### ComfyUI Revision: 2324 [537f35c7] | Released on '2024-07-02'
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/github-stats.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/model-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/alter-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/custom-node-list.json
[ComfyUI-Manager] default cache updated: https://raw.githubusercontent.com/ltdrdata/ComfyUI-Manager/main/extension-node-map.json
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotion\__init__.py", line 4, in <module>
    from .nodes import MimicMotionNode, LoadVideo, PreViewVideo
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotion\nodes.py", line 18, in <module>
    from mimicmotion.pipelines.pipeline_mimicmotion import MimicMotionPipeline
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotion\mimicmotion\pipelines\pipeline_mimicmotion.py", line 9, in <module>
    from diffusers.image_processor import VaeImageProcessor, PipelineImageInput
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\__init__.py", line 4, in <module>
    from .onnx_utils import OnnxRuntimeModel
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\diffusers\onnx_utils.py", line 31, in <module>
    import onnxruntime as ort
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 57, in <module>
    raise import_capi_exception
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\__init__.py", line 23, in <module>
    from onnxruntime.capi._pybind_state import ExecutionMode  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages\onnxruntime\capi\_pybind_state.py", line 32, in <module>
    from .onnxruntime_pybind11_state import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing onnxruntime_pybind11_state: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotion module for custom nodes: DLL load failed while importing onnxruntime_pybind11_state: Une routine d’initialisation d’une bibliothèque de liens dynamiques (DLL) a échoué.
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MuseTalk_FSH\__init__.py", line 1, in <module>
    from .nodes import MuseTalk,LoadVideo,PreViewVideo,CombineAudioVideo,MuseTalkRealTime
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MuseTalk_FSH\nodes.py", line 3, in <module>
    from .inference import MuseTalk_INFER
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MuseTalk_FSH\inference.py", line 14, in <module>
    from mmpose.apis import init_model
ModuleNotFoundError: No module named 'mmpose'

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MuseTalk_FSH module for custom nodes: No module named 'mmpose'
Traceback (most recent call last):
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\nodes.py", line 1906, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UniAnimate\__init__.py", line 5, in <module>
    from modelscope.hub.snapshot_download import snapshot_download
ModuleNotFoundError: No module named 'modelscope'

Cannot import D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UniAnimate module for custom nodes: No module named 'modelscope'
------------------------------------------
Comfyroll Studio v1.76 :  175 Nodes Loaded
------------------------------------------
** For changes, please see patch notes at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/blob/main/Patch_Notes.md
** For help, please see the wiki at https://github.com/Suzie1/ComfyUI_Comfyroll_CustomNodes/wiki
------------------------------------------
!!!VExpress path was added to D:\AI\ComfyUI_windows_portable\python_embeded\Lib\site-packages/VExpress.pth
 if meet `No module` error,try `python main.py` again, don't be foolish to pip install modules
Fetching 19 files: 100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 19/19 [00:00<00:00, 9496.16it/s]

[rgthree] Loaded 40 extraordinary nodes.
[rgthree] Will use rgthree's optimized recursive execution.

WAS Node Suite: OpenCV Python FFMPEG support is enabled
WAS Node Suite Warning: `ffmpeg_bin_path` is not set in `D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui\was_suite_config.json` config file. Will attempt to use system ffmpeg binaries if available.
WAS Node Suite: Finished. Loaded 216 nodes successfully.

        "Art is not what you see, but what you make others see." - Edgar Degas


Import times for custom nodes:
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\efficiency-nodes-comfyui
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-FrameManager
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\websocket_image_save.py
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\sdxl_prompt_styler
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Eagle-PNGInfo
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_controlnet_aux
   0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-UniAnimate
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-animatediff
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Video-Matting
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfy-image-saver
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-browser
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
   0.0 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MuseTalk_FSH
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\rgthree-comfy
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-KJNodes
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_essentials
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
   0.0 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Inspire-Pack
   0.1 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DiffSynth-Studio
   0.1 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-3d-photo-inpainting
   0.1 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-DynamiCrafterWrapper
   0.3 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager
   0.3 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui_segment_anything
   0.4 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-IP_LAP
   0.5 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_V-Express
   1.2 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\was-node-suite-comfyui
   2.7 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Hallo
   2.8 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-I2V-Adapter
   3.1 seconds (IMPORT FAILED): D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-MimicMotion
  33.9 seconds: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\comfyui-art-venture

Starting server

To see the GUI go to: http://127.0.0.1:8188
FETCH DATA from: D:\AI\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
`

**Comment by Hikska** [comment]
what got installed
![Capture d'écran 2024-07-03 160730](https://github.com/AIFSH/ComfyUI-MimicMotion/assets/76734080/60126e76-2a89-493e-8ad8-5d80af0b358b)
for 
![image](https://github.com/AIFSH/ComfyUI-MimicMotion/assets/76734080/3fb09cda-1693-4429-a89c-85ec58bcee83)

**Comment by Hikska** [comment]
i asked Gemini to do a tldr

Persistent Errors

ComfyUI-DiffSynth-Studio: Still the same ImportError: cannot import name 'CannyDetector' from 'controlnet_aux'.
ComfyUI-Hallo, ComfyUI-I2V-Adapter, ComfyUI-MimicMotion: Still show the ImportError: DLL load failed related to onnxruntime.
ComfyUI-IP_LAP: Still shows ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'.
ComfyUI-MuseTalk_FSH: Still shows ModuleNotFoundError: No module named 'mmcv'.
ComfyUI-UniAnimate: Still shows ModuleNotFoundError: No module named 'modelscope'.

**Comment by Haydn-Mann** [comment]
i also kept getting an error where it was not loading.

Installing mimicmotion wrapper from the comfyui manager seemed to solve it

![image](https://github.com/AIFSH/ComfyUI-MimicMotion/assets/93770616/6e3965dd-c535-4f65-9939-6ce5c66de02d)

**Comment by leetraman822** [comment]
> i also kept getting an error where it was not loading.
> 
> Installing mimicmotion wrapper from the comfyui manager seemed to solve it
> 
> ![image](https://private-user-images.githubusercontent.com/93770616/345469632-6e3965dd-c535-4f65-9939-6ce5c66de02d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAwNzIxMzAsIm5iZiI6MTcyMDA3MTgzMCwicGF0aCI6Ii85Mzc3MDYxNi8zNDU0Njk2MzItNmUzOTY1ZGQtYzUzNS00ZjY1LTk5MzktNmNlNWM2NmRlMDJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA0VDA1NDM1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI5Y2Q5NjdjMTgzMDVkNTY3Mzk3ZjUzZDJmZDc5ZTE2ZjVlN2Q0MjdlNDZlMDI5MTEzODdhOTBiOTMwYjY0YzYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.A76E4lbj9SXypaeKA3EhJiwk94NSbtoa1wuDB3ceEhw)

Thank you. Although I tried to install the Kijai's MimicMotionWrapper, it still showing that the MimicMotionNode was missing. I'm not sure why, but now, I use Kijai's workflow and run MimicMotion successfully.

**Comment by leetraman822** [comment]
> i asked Gemini to do a tldr
> 
> Persistent Errors
> 
> ComfyUI-DiffSynth-Studio: Still the same ImportError: cannot import name 'CannyDetector' from 'controlnet_aux'. ComfyUI-Hallo, ComfyUI-I2V-Adapter, ComfyUI-MimicMotion: Still show the ImportError: DLL load failed related to onnxruntime. ComfyUI-IP_LAP: Still shows ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'. ComfyUI-MuseTalk_FSH: Still shows ModuleNotFoundError: No module named 'mmcv'. ComfyUI-UniAnimate: Still shows ModuleNotFoundError: No module named 'modelscope'.

Hi. You can try installing Kijai's MimicMotionWrapper. I used Kijai's workflow and ran MimicMotion successfully. I hope this helps.
