### ISSUE TITLE
运行异常，提示模型文件不存在

### ISSUE THREAD

**Issue by duguyixiaono1** [AIFSH/ComfyUI-MimicMotion#8]
!!! Exception during processing !!!
Traceback (most recent call last):
  File "/root/ComfyUI/execution.py", line 151, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
  File "/root/ComfyUI/execution.py", line 81, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
  File "/root/ComfyUI/execution.py", line 74, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
  File "/root/miniconda3/lib/python3.10/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotion/nodes.py", line 102, in gen_video
    pipeline = create_pipeline(infer_config,device)
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotion/mimicmotion/utils/loader.py", line 43, in create_pipeline
    mimicmotion_models = MimicMotionModel(infer_config.base_model_path).to(device=device).eval()
  File "/root/ComfyUI/custom_nodes/ComfyUI-MimicMotion/mimicmotion/utils/loader.py", line 27, in __init__
    self.image_encoder = CLIPVisionModelWithProjection.from_pretrained(
  File "/root/miniconda3/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2164, in from_pretrained
    raise EnvironmentError(
OSError: Error no file named pytorch_model.bin, tf_model.h5, model.ckpt.index or flax_model.msgpack found in directory /root/ComfyUI/custom_nodes/ComfyUI-MimicMotion/models/stable-video-diffusion-img2vid-xt-1-1.

**Comment by duguyixiaono1** [comment]
我看svd的模型文件没有这些提示的文件啊
https://huggingface.co/stabilityai/stable-video-diffusion-img2vid-xt-1-1/tree/main/image_encoder

**Comment by duguyixiaono1** [comment]
root@autodl-container-97b611a952-c5d90096:~/ComfyUI/custom_nodes/ComfyUI-MimicMotion/models/stable-video-diffusion-img2vid-xt-1-1/image_encoder# lltotal 4
drwxr-xr-x 2 root root  67 Jul  4 17:26 ./
drwxr-xr-x 7 root root 144 Jul  4 17:22 ../
-rw-r--r-- 1 root root 685 Jul  4 16:49 config.json
lrwxrwxrwx 1 root root 166 Jul  4 16:49 model.fp16.safetensors -> ../../../../../../.cache/huggingface/hub/models--weights--stable-video-diffusion-img2vid-xt-1-1/blobs/ae616c24393dd1854372b0639e5541666f7521cbe219669255e865cb7f89466a

**Comment by duguyixiaono1** [comment]
补充一张异常堆栈截图：
<img width="1068" alt="image" src="https://github.com/AIFSH/ComfyUI-MimicMotion/assets/2703461/48a183ae-add8-45c1-983a-56e5928e9f2b">
